[Top]
x_rot = 0
y_rot = 90
z_rot = 90

[Bottom]
x_rot = 0
y_rot = -90
z_rot = 90

[Front]
x_rot = 0
y_rot = 0
z_rot = 0

[Back]
x_rot = 0
y_rot = 0 
z_rot = 180

[Left]
x_rot = 0
y_rot = 90
z_rot = 0

[Right]
x_rot = 0
y_rot = -90
z_rot = 0

["Isometric Front-Right"]
x_rot = 0
y_rot = 45
z_rot = 45

["Isometric Front-Left"]
x_rot = 0
y_rot = 45
z_rot = -45

["Isometric Back-Right"]
x_rot = 0
y_rot = 45
z_rot = 135

["Isometric Back-Left"]
x_rot = 0
y_rot = 45
z_rot = -135
